apiVersion: v1
kind: Service
metadata:
  name: vrising
  namespace: aamoyel
spec:
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
  - name: game
    port: 9876
    targetPort: 9876
    nodePort: 32076
    protocol: UDP
  - name: query
    port: 9877
    targetPort: 9877
    nodePort: 32077
    protocol: UDP
  selector:
    kubevirt.io/vm: vrising
  type: NodePort
