apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: glb-services
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.254.254.100"
spec:
  type: LoadBalancer
  ports:
  - name: api
    port: 443
    targetPort: 8200
    protocol: TCP
  selector:
    vm.kubevirt.io/name: vault
