apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: golinks
  namespace: glb-services
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
