apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: kube127-ubuntu2210
  namespace: default
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: ''
spec:
  source:
    registry:
      url: "docker://barthv/cloud-ubuntu-2204:v1.27.2"
  pvc:
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
