apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 1m
  path: ./bootstrap/cloudnative-pg
  prune: false
  sourceRef:
    kind: GitRepository
    name: infra
