apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-controller
  namespace: flux-system
spec:
  interval: 1m
  path: ./bootstrap/ingress-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
