apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kamaji
  namespace: flux-system
spec:
  interval: 10m
  url: https://clastix.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kamaji
  namespace: flux-system
spec:
  targetNamespace: kamaji-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: kamaji
      version: v0.12.5
      sourceRef:
        kind: HelmRepository
        name: kamaji
  interval: 10m
  valuesFrom:
  - kind: ConfigMap
    name: kamaji-values
    valuesKey: values.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kamaji-values
  namespace: flux-system
data:
  values.yaml: |
    etcd:
      deploy: false
    datastore:
      nameOverride: postgres
      driver: PostgreSQL
      endpoints[0]: postgres-rw.kamaji-system.svc:5432
      basicAuth:
        usernameSecret:
          name: postgres-superuser
          namespace: kamaji-system
          keyPath: username
        passwordSecret:
          name: postgres-superuser
          namespace: kamaji-system
          keyPath: password
      tlsConfig:
        certificateAuthority:
          certificate:
            name: postgres-ca
            namespace: kamaji-system
            keyPath: ca.crt
          privateKey:
            name: postgres-ca
            namespace: kamaji-system
            keyPath: ca.key
        clientCertificate:
          certificate:
            name: postgres-default-root-cert
            namespace: kamaji-system
            keyPath: tls.crt
          privateKey:
            name: postgres-default-root-cert
            namespace: kamaji-system
            keyPath: tls.key
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kamaji-db
  namespace: flux-system
spec:
  interval: 5m
  path: ./bootstrap/kamaji-db
  prune: false
  sourceRef:
    kind: GitRepository
    name: infra
