apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kamaji
  namespace: flux-system
spec:
  interval: 10m
  url: https://clastix.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kamaji
  namespace: flux-system
spec:
  targetNamespace: kamaji-system
  chart:
    spec:
      chart: kamaji
      version: v0.12.5
      sourceRef:
        kind: HelmRepository
        name: kamaji
  interval: 10m
