apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kamaji
  namespace: flux-system
spec:
  interval: 10m
  url: https://clastix.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kamaji
  namespace: flux-system
spec:
  targetNamespace: kamaji-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: kamaji
      version: v0.12.5
      sourceRef:
        kind: HelmRepository
        name: kamaji
  interval: 10m
  values:
    etcd.deploy: false
    datastore.driver: PostgreSQL
    datastore.endpoints[0]: postgres.kamaji-system.svc:5432
    datastore.basicAuth.usernameSecret.name: postgres
    datastore.basicAuth.usernameSecret.namespace: kamaji-system
    datastore.basicAuth.usernameSecret.keyPath: username
    datastore.basicAuth.passwordSecret.name: postgres
    datastore.basicAuth.passwordSecret.namespace: kamaji-system
    datastore.basicAuth.passwordSecret.keyPath: password
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kamaji-db
  namespace: flux-system
spec:
  interval: 5m
  path: ./bootstrap/kamaji-db
  prune: false
  sourceRef:
    kind: GitRepository
    name: infra