apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubevirt-manager
  namespace: flux-system
spec:
  interval: 5m
  path: ./tools/kubevirt-manager
  prune: false
  sourceRef:
    kind: GitRepository
    name: infra
