apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: unsealer-operator
  namespace: flux-system
spec:
  interval: 30m
  path: ./tools/unsealer-operator
  prune: false
  sourceRef:
    kind: GitRepository
    name: infra
