apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.13.4
        args:
        - --source=ingress
        - --source=service
        - --provider=pdns
        - --domain-filter=didactiklabs.corp
        - --log-level=debug
        - --interval=30s
        env:
        - name: EXTERNAL_DNS_PDNS_SERVER
          value: "http://powerdns-api.glb-services.svc"
        - name: EXTERNAL_DNS_PDNS_API_KEY
          valueFrom:
            secretKeyRef:
              name: external-dns
              key: api_key           
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: external-dns
  data:
  - secretKey: api_key
    remoteRef:
      key: infra/powerdns/server
      property: api_key
