apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: aam-prod
  namespace: aamoyel
  labels:
    cni: cilium
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.243.0.0/16
    services:
      cidrBlocks:
      - 10.95.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: aam-prod-cp
    namespace: aamoyel
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KubevirtCluster
    name: aam-prod
    namespace: aamoyel
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  name: aam-prod
  namespace: aamoyel
spec:
  controlPlaneServiceTemplate:
    metadata:
      annotations:
        metallb.universe.tf/address-pool: production
        metallb.universe.tf/loadBalancerIPs: 192.168.1.100
    spec:
      type: LoadBalancer
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: aam-prod-cp
  namespace: aamoyel
spec:
  template:
    spec:
      virtualMachineTemplate:
        metadata:
          namespace: aamoyel
        spec:
          runStrategy: Always
          template:
            spec:
              domain:
                cpu:
                  cores: 4
                devices:
                  interfaces:
                  - name: default
                    bridge: {}
                  disks:
                  - disk:
                      bus: virtio
                    name: data
                memory:
                  guest: 6Gi
              evictionStrategy: External
              networks:
              - name: default
                pod: {}
              readinessProbe:
                initialDelaySeconds: 200
                periodSeconds: 20
                timeoutSeconds: 10
                failureThreshold: 3
                successThreshold: 1
                tcpSocket:
                  port: 6443
              volumes:
              - name: data
                dataVolume:
                  name: data
          dataVolumeTemplates:
          - metadata:
              name: data
            spec:
              pvc:
                accessModes:
                - ReadWriteOnce
                resources:
                  requests:
                    storage: 20G
              source:
                pvc:
                  namespace: aamoyel
                  name: capi-ubuntu-template
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: aam-prod-cp
  namespace: aamoyel
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      networking:
        dnsDomain: aam-prod.aamoyel.local
        podSubnet: 10.243.0.0/16
        serviceSubnet: 10.95.0.0/16
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
      skipPhases:
      - addon/kube-proxy
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: KubevirtMachineTemplate
      name: aam-prod-cp
      namespace: aamoyel
  replicas: 3
  version: v1.26.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: aam-prod-wk
  namespace: aamoyel
spec:
  template:
    spec:
      virtualMachineTemplate:
        metadata:
          namespace: aamoyel
        spec:
          runStrategy: Always
          template:
            spec:
              domain:
                cpu:
                  cores: 4
                devices:
                  disks:
                  - disk:
                      bus: virtio
                    name: data
                memory:
                  guest: 8Gi
              evictionStrategy: External
              volumes:
              - name: data
                containerDisk:
                  image: barthv/cloud-ubuntu-2204:0.3.1
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: aam-prod-wk
  namespace: aamoyel
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs: {}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: aam-prod-wk
  namespace: aamoyel
spec:
  clusterName: aam-prod
  replicas: 3
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: aam-prod-wk
          namespace: aamoyel
      clusterName: aam-prod
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: KubevirtMachineTemplate
        name: aam-prod-wk
        namespace: aamoyel
      version: v1.26.0
