apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: capi-ubuntu-template
  namespace: aamoyel
spec:
  source:
    registry:
      url: "docker://barthv/cloud-ubuntu-2204:0.3.1"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 12G
